services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  airflow-init:
    build: .
    entrypoint: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@example.com --password admin &&
      airflow connections delete smtp_default || true &&
      airflow connections add smtp_default
        --conn-type smtp
        --conn-host smtp.gmail.com
        --conn-login <YOUR-EMAIL-HERE>
        --conn-password <YOUR-PASSWORD-HERE>
        --conn-port 587
        --conn-extra '{\"starttls\": true}'
      "
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "d4f5g6h7j8k9l0q1w2e3r4t5y6u7i8o9p0a1s2d3f4g5"
      #email config      
      AIRFLOW_CONN_SMTP_DEFAULT: "smtp://pedromenegat%40gmail.com:<YOUR-PASSWORD-HERE>@smtp.gmail.com:587/?starttls=true"
      AIRFLOW__EMAIL__EMAIL_BACKEND: airflow.utils.email.send_email_smtp
      AIRFLOW__EMAIL__EMAIL_CONN_ID: "smtp_default"
      AIRFLOW__SMTP__SMTP_HOST: "smtp.gmail.com"
      AIRFLOW__SMTP__SMTP_STARTTLS: "True"
      AIRFLOW__SMTP__SMTP_SSL: "False"
      AIRFLOW__SMTP__SMTP_USER: "<YOUR-EMAIL-HERE>"
      AIRFLOW__SMTP__SMTP_PASSWORD: "<YOUR-PASSWORD-HERE>"
      AIRFLOW__SMTP__SMTP_PORT: "587"
      AIRFLOW__SMTP__SMTP_MAIL_FROM: "<YOUR-EMAIL-HERE>"

    depends_on:
      - postgres

  airflow-webserver:
    build: .
    command: webserver
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "d4f5g6h7j8k9l0q1w2e3r4t5y6u7i8o9p0a1s2d3f4g5"
      AIRFLOW__EMAIL__EMAIL_BACKEND: airflow.utils.email.send_email_smtp
      AIRFLOW__EMAIL__EMAIL_CONN_ID: "smtp_default"
      AIRFLOW__SMTP__SMTP_HOST: smtp.gmail.com
      AIRFLOW__SMTP__SMTP_PORT: 587
      AIRFLOW__SMTP__SMTP_STARTTLS: "True"
      AIRFLOW__SMTP__SMTP_USER: <YOUR-EMAIL-HERE>
      AIRFLOW__SMTP__SMTP_PASSWORD: <YOUR-PASSWORD-HERE>
      AIRFLOW__SMTP__SMTP_MAIL_FROM: <YOUR-EMAIL-HERE>
    user: "50000:0"
    depends_on:
      - postgres
      - airflow-init
    volumes:
      - ./dags:/opt/airflow/dags
      - ./storage:/opt/airflow/dags/bronze/storage
      - ./dags/bronze/storage:/opt/airflow/dags/bronze/storage
      - ./storage:/opt/airflow/dags/silver/storage
      - ./dags/silver/storage:/opt/airflow/dags/silver/storage


  airflow-scheduler:
    build: .
    command: scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "d4f5g6h7j8k9l0q1w2e3r4t5y6u7i8o9p0a1s2d3f4g5"
      AIRFLOW__EMAIL__EMAIL_BACKEND: airflow.utils.email.send_email_smtp
      AIRFLOW__EMAIL__EMAIL_CONN_ID: "smtp_default"
      AIRFLOW__SMTP__SMTP_HOST: smtp.gmail.com
      AIRFLOW__SMTP__SMTP_PORT: 587
      AIRFLOW__SMTP__SMTP_STARTTLS: "True"
      AIRFLOW__SMTP__SMTP_USER: <YOUR-EMAIL-HERE>
      AIRFLOW__SMTP__SMTP_PASSWORD: <YOUR-PASSWORD-HERE>
      AIRFLOW__SMTP__SMTP_MAIL_FROM: <YOUR-EMAIL-HERE>
    user: "50000:0"
    depends_on:
      - postgres
      - airflow-init
    volumes:
      - ./dags:/opt/airflow/dags
      - ./storage:/opt/airflow/dags/bronze/storage
      - ./dags/bronze/storage:/opt/airflow/dags/bronze/storage
      - ./storage:/opt/airflow/dags/silver/storage
      - ./dags/silver/storage:/opt/airflow/dags/silver/storage

volumes:
  postgres-db-volume: